FROM node:22 AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm generate

FROM node:22
RUN corepack enable
WORKDIR /app
COPY . /app
COPY --from=build /app/node_modules ./node_modules
RUN corepack enable

RUN apt-get update
# Install mysqldump
RUN apt-get install -y default-mysql-client

# Install pgdump
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ bookworm-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
RUN apt-get update
RUN apt-get install --install-recommends -y postgresql-client

# Install mongodump
RUN  wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | apt-key add - 
RUN echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
RUN apt-get update 
RUN apt-get install -y mongodb-database-tools

# Start project
CMD [ "pnpm", "start:dev" ]