// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.4
//   protoc               v5.28.2
// source: proto/backup.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "backup";

export interface BackupFile {
  id: string;
  dbName: string;
  fileName: string;
  path: string;
  size: string;
  createdAt: number;
}

export interface GetBackupRequest {
  offset: number;
  limit: number;
  dbName: string;
  startDate: number;
  endDate: number;
}

export interface GetBackupResponse {
  files: BackupFile[];
  total: number;
}

export interface DumpRequest {
  username: string;
  password: string;
  host: string;
  port: string;
  dbName: string;
}

export const BACKUP_PACKAGE_NAME = "backup";

export interface BackupClient {
  findAll(request: GetBackupRequest): Observable<GetBackupResponse>;

  dump(request: DumpRequest): Observable<BackupFile>;
}

export interface BackupController {
  findAll(request: GetBackupRequest): Promise<GetBackupResponse> | Observable<GetBackupResponse> | GetBackupResponse;

  dump(request: DumpRequest): Promise<BackupFile> | Observable<BackupFile> | BackupFile;
}

export function BackupControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findAll", "dump"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Backup", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Backup", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BACKUP_SERVICE_NAME = "Backup";
